// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO Documents (Guid, Title, Description, Content)
VALUES ($1, $2, $3, $4)
RETURNING Id, Guid, Title, Description, Content, Created
`

type CreateDocumentParams struct {
	Guid        string
	Title       string
	Description string
	Content     string
}

// Document CRUD
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Guid,
		arg.Title,
		arg.Description,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Created,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM Documents 
WHERE Guid = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, guid string) error {
	_, err := q.db.Exec(ctx, deleteDocument, guid)
	return err
}

const getDocumentByGuid = `-- name: GetDocumentByGuid :one
SELECT Id, Guid, Title, Description, Content, Created 
FROM Documents 
WHERE Guid = $1 LIMIT 1
`

func (q *Queries) GetDocumentByGuid(ctx context.Context, guid string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByGuid, guid)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Created,
	)
	return i, err
}

const getDocumentsByAuthors = `-- name: GetDocumentsByAuthors :many
SELECT d.Id, d.Guid, d.Title, d.Description, d.Content, d.Created
FROM Documents d
JOIN Document_Authors da ON d.Id = da.DocumentId
JOIN Authors a ON da.AuthorId = a.Id
WHERE a.Name = ANY($1::text[])
`

// AI queriy method tools as well as ui interface method tools
func (q *Queries) GetDocumentsByAuthors(ctx context.Context, dollar_1 []string) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByAuthors, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByRelatedLinks = `-- name: GetDocumentsByRelatedLinks :many
SELECT DISTINCT d.Id, d.Guid, d.Title, d.Description, d.Content, d.Created
FROM Documents d
JOIN Document_Links dl ON d.Id = dl.DocumentId
JOIN Links l ON dl.LinkId = l.Id
WHERE l.Link LIKE $1
`

func (q *Queries) GetDocumentsByRelatedLinks(ctx context.Context, link string) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByRelatedLinks, link)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByTags = `-- name: GetDocumentsByTags :many
SELECT d.Id, d.Guid, d.Title, d.Description, d.Content, d.Created
FROM Documents d
JOIN Document_Tags dt ON d.Id = dt.DocumentId
JOIN Tags t ON dt.TagId = t.Id
WHERE t.Name = ANY($1::text[])
`

func (q *Queries) GetDocumentsByTags(ctx context.Context, dollar_1 []string) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByTimeRange = `-- name: GetDocumentsByTimeRange :many
SELECT Id, Guid, Title, Description, Content, Created 
FROM Documents
WHERE Created >= $1 AND Created <= $2
ORDER BY Created DESC
`

type GetDocumentsByTimeRangeParams struct {
	Created   pgtype.Timestamptz
	Created_2 pgtype.Timestamptz
}

func (q *Queries) GetDocumentsByTimeRange(ctx context.Context, arg GetDocumentsByTimeRangeParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByTimeRange, arg.Created, arg.Created_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateAuthor = `-- name: GetOrCreateAuthor :one
INSERT INTO Authors (Name) 
VALUES ($1)
ON CONFLICT (Name) DO UPDATE SET Name = EXCLUDED.Name
RETURNING Id, Name
`

// Author, Tag, Link creating when Documents are creating
func (q *Queries) GetOrCreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRow(ctx, getOrCreateAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrCreateLink = `-- name: GetOrCreateLink :one
INSERT INTO Links (Link) 
VALUES ($1)
ON CONFLICT (Link) DO UPDATE SET Link = EXCLUDED.Link
RETURNING Id, Link
`

func (q *Queries) GetOrCreateLink(ctx context.Context, link string) (Link, error) {
	row := q.db.QueryRow(ctx, getOrCreateLink, link)
	var i Link
	err := row.Scan(&i.ID, &i.Link)
	return i, err
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO Tags (Name) 
VALUES ($1)
ON CONFLICT (Name) DO UPDATE SET Name = EXCLUDED.Name
RETURNING Id, Name
`

func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const linkDocumentToAuthor = `-- name: LinkDocumentToAuthor :exec
INSERT INTO Document_Authors (DocumentId, AuthorId)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkDocumentToAuthorParams struct {
	Documentid int64
	Authorid   int64
}

// These will be in a transaction
func (q *Queries) LinkDocumentToAuthor(ctx context.Context, arg LinkDocumentToAuthorParams) error {
	_, err := q.db.Exec(ctx, linkDocumentToAuthor, arg.Documentid, arg.Authorid)
	return err
}

const linkDocumentToLink = `-- name: LinkDocumentToLink :exec
INSERT INTO Document_Links (DocumentId, LinkId)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkDocumentToLinkParams struct {
	Documentid int64
	Linkid     int64
}

func (q *Queries) LinkDocumentToLink(ctx context.Context, arg LinkDocumentToLinkParams) error {
	_, err := q.db.Exec(ctx, linkDocumentToLink, arg.Documentid, arg.Linkid)
	return err
}

const linkDocumentToTag = `-- name: LinkDocumentToTag :exec
INSERT INTO Document_Tags (DocumentId, TagId)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkDocumentToTagParams struct {
	Documentid int64
	Tagid      int64
}

func (q *Queries) LinkDocumentToTag(ctx context.Context, arg LinkDocumentToTagParams) error {
	_, err := q.db.Exec(ctx, linkDocumentToTag, arg.Documentid, arg.Tagid)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE Documents
SET Title = $2, Description = $3, Content = $4
WHERE Guid = $1
RETURNING Id, Guid, Title, Description, Content, Created
`

type UpdateDocumentParams struct {
	Guid        string
	Title       string
	Description string
	Content     string
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Guid,
		arg.Title,
		arg.Description,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Created,
	)
	return i, err
}
