// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
}

type Document struct {
	ID          int64
	Guid        string
	Title       string
	Description string
	Content     string
	Created     pgtype.Timestamptz
}

type DocumentAuthor struct {
	Documentid int64
	Authorid   int64
}

type DocumentLink struct {
	Documentid int64
	Linkid     int64
}

type DocumentTag struct {
	Documentid int64
	Tagid      int64
}

type Link struct {
	ID   int64
	Link string
}

type Tag struct {
	ID   int64
	Name string
}
